version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoing_php
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=mongoadmin
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=todo_app

  mongodb:
    image: mongo:5
    container_name: todoing_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongodb_data: