name: PHP Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5
        env:
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: 123456
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand({serverStatus:1}).ok' | mongosh --quiet --username mongoadmin --password 123456 admin --eval 'quit(db.runCommand({serverStatus:1}).ok ? 0 : 1)'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongodb-1.13.0
          coverage: xdebug
          tools: composer:v2

      - name: Check PHP and MongoDB versions
        run: |
          php -v
          php -m | grep mongodb
          php -i | grep -i mongodb

      - name: Validate composer.json
        run: composer validate --no-strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Use MongoDB Shell from service container
        run: |
          # Utilizamos el mongosh del contenedor de MongoDB
          docker exec -i $(docker ps -q --filter ancestor=mongo:5) mongosh --host localhost --port 27017 -u mongoadmin -p 123456 --eval "db = db.getSiblingDB('todo_app_test'); db.createCollection('usuarios'); db.createCollection('tareas');"

      - name: Run test suite
        run: composer run-script test
